name: scrobblenaut
description: A deadly simple Last.FM API Wrapper for Dart.
version: 1.0.0
homepage: https://github.com/Nebulino/Scrobblenaut
issue_tracker: https://github.com/Nebulino/Scrobblenaut/issues

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  meta: ^1.1.8
  dio: ^3.0.9
  crypto: ^2.1.4
  xml: ^4.1.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.2
  json_serializable: ^3.3.0
  build_runner: ^1.8.0
