name: scrobblenaut
description: A deadly simple LastFM API Wrapper for Dart. So deadly simple that it's gonna hit the mark.
version: 2.0.5+1
homepage: https://github.com/Nebulino/Scrobblenaut
issue_tracker: https://github.com/Nebulino/Scrobblenaut/issues

environment:
  sdk: ^2.16.2

dependencies:
  meta: ^1.8.0
  json_annotation: ^4.5.0
  convert: ^3.0.2
  dio: ^4.0.6
  crypto: ^3.0.2
  xml: ^6.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.2
  json_serializable: ^6.2.0
  build_runner: ^2.1.11
